# Base image ufficiale AWS Lambda Python 3.10
FROM public.ecr.aws/lambda/python:3.10

# Imposta la directory di lavoro
WORKDIR /var/task

# Copia i file necessari
COPY web/utility/lambda_fulfillment_check.py ${LAMBDA_TASK_ROOT}/
COPY config/settings.py ${LAMBDA_TASK_ROOT}/config/
COPY config/__init__.py ${LAMBDA_TASK_ROOT}/config/
COPY web/utility/shopify-lambda-integration-ff8f0760340f.json ${LAMBDA_TASK_ROOT}/

# Installa le dipendenze
RUN pip install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org && \
    pip install requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client --trusted-host pypi.org --trusted-host files.pythonhosted.org -t ${LAMBDA_TASK_ROOT}

# Comando di default per Lambda
CMD ["lambda_fulfillment_check.lambda_handler"]
